spring.application.name=FirstJobApplication

## H2 In-Memory Database
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Auto-create tables
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Enable H2 web console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# postgresql

spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=sarkar
spring.datasource.password=
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


